name: Salesforce CI/CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SF_USERNAME: ${{ secrets.SF_USERNAME }}
      SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
      SF_SERVER_KEY: ${{ secrets.SF_SERVER_KEY }}
      SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 1️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 2️⃣ Install Salesforce CLI (official action)
      - name: Install Salesforce CLI
        uses: salesforcecli/sfdx-action@v1

      # 3️⃣ Write private key to file
      - name: Write private key to file
        run: |
          echo "${SF_SERVER_KEY}" > server.key
          chmod 600 server.key

      # 4️⃣ Authenticate to Salesforce
      - name: Authenticate to Salesforce
        run: |
          sfdx auth:jwt:grant \
            --clientid $SF_CLIENT_ID \
            --jwtkeyfile server.key \
            --username $SF_USERNAME \
            --instanceurl $SF_INSTANCE_URL

      # 5️⃣ Display org info (debug)
      - name: Display org info
        run: |
          sfdx force:org:display --targetusername $SF_USERNAME

      # 6️⃣ Check-only deploy
      - name: Check-only deploy
        id: check_deploy
        run: |
          sfdx force:source:deploy -p force-app --targetusername $SF_USERNAME --checkonly --json > result.json
          cat result.json

      # 7️⃣ Actual deploy if check-only passes
      - name: Deploy to Salesforce
        if: ${{ success() }}
        run: |
          sfdx force:source:deploy -p force-app --targetusername $SF_USERNAME --json
