name: Salesforce CI/CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SF_USERNAME: ${{ secrets.SF_USERNAME }}
      SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
      SF_SERVER_KEY: ${{ secrets.SF_SERVER_KEY }}
      SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli --global

      - name: Write private key
        run: |
          echo "${SF_SERVER_KEY}" | tr -d '\r' > server.key
          chmod 600 server.key

      - name: Authenticate to Salesforce
        run: |
          sfdx force:auth:jwt:grant \
            --clientid $SF_CLIENT_ID \
            --jwtkeyfile server.key \
            --username $SF_USERNAME \
            --instanceurl $SF_INSTANCE_URL
          sfdx force:org:list --all

      - name: Display org info (debug)
        run: |
          sfdx force:org:display --targetusername $SF_USERNAME

      - name: Check-only deploy
        id: check_deploy
        run: sfdx force:source:deploy -p force-app --targetusername $SF_USERNAME --checkonly --json


      - name: Actual deploy if check-only passes
        if: ${{ success() }}
        run: |
          sfdx force:source:deploy -p force-app --targetusername $SF_USERNAME --json
