name: Debug Salesforce Credentials

on:
  workflow_dispatch:

jobs:
  debug-credentials:
    runs-on: ubuntu-latest
    env:
      SF_USERNAME: ${{ secrets.SF_USERNAME }}
      SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
      SF_SERVER_KEY: ${{ secrets.SF_SERVER_KEY }}
      SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show Environment Variables
        run: |
          echo "SF_USERNAME=$SF_USERNAME"
          echo "SF_CLIENT_ID=$SF_CLIENT_ID"
          echo "SF_INSTANCE_URL=$SF_INSTANCE_URL"
          echo "SF_SERVER_KEY is set? $( [ -n "$SF_SERVER_KEY" ] && echo yes || echo no )"
